# using try except we can check a block of code it it shows error or not
try:
    print(x)  # this will show error as x is not defined but in try statement it checkes the statement and if there is error it exicuted the except statement
except:
    print("error occured")



# you can also check for sertain type of errors n